CREATE TABLE "zmanger_files" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_files_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"content" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"parentId" integer
);
--> statement-breakpoint
CREATE TABLE "zmanger_review" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_review_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"userId" varchar(64),
	"firstName" varchar(128),
	"lastName" varchar(128),
	"imageUrl" varchar(512),
	"title" varchar(256),
	"rating" integer,
	"description" varchar(512)
);
--> statement-breakpoint
CREATE TABLE "zmanger_test_batch" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_test_batch_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"subject" varchar(256) NOT NULL,
	"language" varchar(50) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zmanger_test" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_test_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"topOfFile" text NOT NULL,
	"aboveMain" text NOT NULL,
	"main" text NOT NULL,
	"stdin" text NOT NULL,
	"expectedOutput" text[] NOT NULL,
	"hidden" boolean DEFAULT false NOT NULL,
	"testBatchId" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "zmanger_files" ADD CONSTRAINT "zmanger_files_parentId_zmanger_files_id_fk" FOREIGN KEY ("parentId") REFERENCES "public"."zmanger_files"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zmanger_test" ADD CONSTRAINT "zmanger_test_testBatchId_zmanger_test_batch_id_fk" FOREIGN KEY ("testBatchId") REFERENCES "public"."zmanger_test_batch"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_id_idx_files" ON "zmanger_files" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "zmanger_review" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "name_idx" ON "zmanger_test_batch" USING btree ("name");--> statement-breakpoint
CREATE INDEX "test_batch_id_idx" ON "zmanger_test" USING btree ("testBatchId");