CREATE TABLE "zmanger_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text,
	"type" varchar(50) DEFAULT 'info' NOT NULL,
	"actionUrl" varchar(512),
	"actionLabel" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX "created_at_idx_notifications" ON "zmanger_notification" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "type_idx_notifications" ON "zmanger_notification" USING btree ("type");