CREATE TABLE "zmanger_user_submission_test" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_user_submission_test_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userSubmissionId" integer NOT NULL,
	"testId" integer NOT NULL,
	"compileOutput" text NOT NULL,
	"stdout" text NOT NULL,
	"stderr" text NOT NULL,
	"time" real NOT NULL,
	"runtimeStatus" integer NOT NULL,
	"submissionStatus" integer NOT NULL,
	"description" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zmanger_user_submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zmanger_user_submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(64) NOT NULL,
	"testBatchId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "zmanger_user_submission_test" ADD CONSTRAINT "zmanger_user_submission_test_userSubmissionId_zmanger_user_submission_id_fk" FOREIGN KEY ("userSubmissionId") REFERENCES "public"."zmanger_user_submission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zmanger_user_submission_test" ADD CONSTRAINT "zmanger_user_submission_test_testId_zmanger_test_id_fk" FOREIGN KEY ("testId") REFERENCES "public"."zmanger_test"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "zmanger_user_submission" ADD CONSTRAINT "zmanger_user_submission_testBatchId_zmanger_test_batch_id_fk" FOREIGN KEY ("testBatchId") REFERENCES "public"."zmanger_test_batch"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_submission_id_idx" ON "zmanger_user_submission_test" USING btree ("userSubmissionId");--> statement-breakpoint
CREATE INDEX "test_id_idx_submission_tests" ON "zmanger_user_submission_test" USING btree ("testId");--> statement-breakpoint
CREATE INDEX "submission_status_idx" ON "zmanger_user_submission_test" USING btree ("submissionStatus");--> statement-breakpoint
CREATE INDEX "user_id_idx_submissions" ON "zmanger_user_submission" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "test_batch_id_idx_submissions" ON "zmanger_user_submission" USING btree ("testBatchId");--> statement-breakpoint
CREATE INDEX "user_test_batch_idx_submissions" ON "zmanger_user_submission" USING btree ("userId","testBatchId");