import "./styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Provider from "./_components/theme-provider";
import { QueryProvider } from "./providers/query-provider";
import { Toaster } from "app/_components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
	title: "Zmanger",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/logo-white.png" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider
			appearance={{
				cssLayerName: "clerk",
				baseTheme: dark,
			}}
		>
			<html lang="en">
				<body className={`${geist.variable}`}>
					<div
						className="fixed -z-10 inset-0 bg-cover bg-no-repeat bg-center"
						style={{ backgroundImage: "url('/bg-blurred-darker.png')" }}
					/>
					<Provider>
						<QueryProvider>{children}</QueryProvider>
					</Provider>
					<SpeedInsights />
				</body>
			</html>
		</ClerkProvider>
	);
}
